# YAML EXPLANATION FILE #

Name: DOSUIBAN
Languages: Python,Shell-script,Javascript,Php,Css,Powershell,Batch,C++,Java
Python-Version: Python 3 
Original Creator: Luca Garofalo (Lucksi)
Author: Luca Garofalo (Lucksi)
Copyright: (C) 2021-2024 Lucksi <lukege287@gmail.com>
Copyright-Years: 2021,2022,2023,2024
Project-site: https://lucksi.github.io/DOSUIBAN
Download: git clone https://github.com/Lucksi/DOSUIBAN
Platforms: Linux/MacOS/Termux/Windows
Version: T.G.D-1.0.4
License: GNU General Public License v3.0
